//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.6.1590.0.
// 
namespace Sysmex.Crm.Plugins.Common {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://Microsoft.LobServices.Sap/2007/03/Rfc/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://Microsoft.LobServices.Sap/2007/03/Rfc/", IsNullable=false)]
    public partial class Z_BIZ_BAPI_CONTRACT_CREATE1 {
        
        private string tRANSACTION_IDField;
        
        private ZBAPI_CON_HEADER cONTRACT_HEADERField;
        
        private ZBAPI_CON_ITEM[] cONTRACT_ITEMField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string TRANSACTION_ID {
            get {
                return this.tRANSACTION_IDField;
            }
            set {
                this.tRANSACTION_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ZBAPI_CON_HEADER CONTRACT_HEADER {
            get {
                return this.cONTRACT_HEADERField;
            }
            set {
                this.cONTRACT_HEADERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://Microsoft.LobServices.Sap/2007/03/Types/Rfc/", IsNullable=false)]
        public ZBAPI_CON_ITEM[] CONTRACT_ITEM {
            get {
                return this.cONTRACT_ITEMField;
            }
            set {
                this.cONTRACT_ITEMField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Microsoft.LobServices.Sap/2007/03/Types/Rfc/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://Microsoft.LobServices.Sap/2007/03/Types/Rfc/", IsNullable=true)]
    public partial class ZBAPI_CON_HEADER {
        
        private string dOC_TYPEField;
        
        private string sALES_ORGField;
        
        private string dISTR_CHANField;
        
        private string sOLD_TO_PARTYField;
        
        private string sHIP_TO_PARTYField;
        
        private string bILL_TO_PARTYField;
        
        private string pAYERField;
        
        private string pURCH_NO_CField;
        
        private string pURCH_DATEField;
        
        private string zCONTRACT_TERMField;
        
        private string pRICE_DATEField;
        
        private string oRD_REASONField;
        
        private string vBELN_GRPField;
        
        private string aDD_VAL_DYField;
        
        private string sHIP_TOField;
        
        private string zCRM_IDField;
        
        private string zSITESField;
        
        private string zTCOUNTField;
        
        private string zSTCOMField;
        
        private string zMINMBILLField;
        
        private System.Nullable<decimal> zKBETRField;
        
        private bool zKBETRFieldSpecified;
        
        private string zCONIN5Field;
        
        private string zCONIN4Field;
        
        private string zCONIN6Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DOC_TYPE {
            get {
                return this.dOC_TYPEField;
            }
            set {
                this.dOC_TYPEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string SALES_ORG {
            get {
                return this.sALES_ORGField;
            }
            set {
                this.sALES_ORGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DISTR_CHAN {
            get {
                return this.dISTR_CHANField;
            }
            set {
                this.dISTR_CHANField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string SOLD_TO_PARTY {
            get {
                return this.sOLD_TO_PARTYField;
            }
            set {
                this.sOLD_TO_PARTYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string SHIP_TO_PARTY {
            get {
                return this.sHIP_TO_PARTYField;
            }
            set {
                this.sHIP_TO_PARTYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string BILL_TO_PARTY {
            get {
                return this.bILL_TO_PARTYField;
            }
            set {
                this.bILL_TO_PARTYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PAYER {
            get {
                return this.pAYERField;
            }
            set {
                this.pAYERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PURCH_NO_C {
            get {
                return this.pURCH_NO_CField;
            }
            set {
                this.pURCH_NO_CField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PURCH_DATE {
            get {
                return this.pURCH_DATEField;
            }
            set {
                this.pURCH_DATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ZCONTRACT_TERM {
            get {
                return this.zCONTRACT_TERMField;
            }
            set {
                this.zCONTRACT_TERMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PRICE_DATE {
            get {
                return this.pRICE_DATEField;
            }
            set {
                this.pRICE_DATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ORD_REASON {
            get {
                return this.oRD_REASONField;
            }
            set {
                this.oRD_REASONField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string VBELN_GRP {
            get {
                return this.vBELN_GRPField;
            }
            set {
                this.vBELN_GRPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ADD_VAL_DY {
            get {
                return this.aDD_VAL_DYField;
            }
            set {
                this.aDD_VAL_DYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string SHIP_TO {
            get {
                return this.sHIP_TOField;
            }
            set {
                this.sHIP_TOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ZCRM_ID {
            get {
                return this.zCRM_IDField;
            }
            set {
                this.zCRM_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ZSITES {
            get {
                return this.zSITESField;
            }
            set {
                this.zSITESField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ZTCOUNT {
            get {
                return this.zTCOUNTField;
            }
            set {
                this.zTCOUNTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ZSTCOM {
            get {
                return this.zSTCOMField;
            }
            set {
                this.zSTCOMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ZMINMBILL {
            get {
                return this.zMINMBILLField;
            }
            set {
                this.zMINMBILLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> ZKBETR {
            get {
                return this.zKBETRField;
            }
            set {
                this.zKBETRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ZCONIN5 {
            get {
                return this.zCONIN5Field;
            }
            set {
                this.zCONIN5Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ZCONIN4 {
            get {
                return this.zCONIN4Field;
            }
            set {
                this.zCONIN4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ZCONIN6 {
            get {
                return this.zCONIN6Field;
            }
            set {
                this.zCONIN6Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Microsoft.LobServices.Sap/2007/03/Types/Rfc/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://Microsoft.LobServices.Sap/2007/03/Types/Rfc/", IsNullable=true)]
    public partial class ZBAPI_RETURN {
        
        private string tYPEField;
        
        private string mESSAGEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string TYPE {
            get {
                return this.tYPEField;
            }
            set {
                this.tYPEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string MESSAGE {
            get {
                return this.mESSAGEField;
            }
            set {
                this.mESSAGEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Microsoft.LobServices.Sap/2007/03/Types/Rfc/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://Microsoft.LobServices.Sap/2007/03/Types/Rfc/", IsNullable=true)]
    public partial class ZBAPI_CON_ITEM {
        
        private string mATERIAL_NUMBERField;
        
        private System.Nullable<decimal> tARGET_QUANTITYField;

        private bool tARGET_QUANTITYFieldSpecified;
                
        private string uOMField;

        private string lINEITEM_IDField;

        private string sHORT_TEXTField;
        
        private System.Nullable<decimal> pRICEField;
        
        private bool pRICEFieldSpecified;
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string LINEITEM_ID
        {
            get
            {
                return this.lINEITEM_IDField;
            }
            set
            {
                this.lINEITEM_IDField = value;
            }
        }
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string MATERIAL_NUMBER {
            get {
                return this.mATERIAL_NUMBERField;
            }
            set {
                this.mATERIAL_NUMBERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> TARGET_QUANTITY {
            get {
                return this.tARGET_QUANTITYField;
            }
            set {
                this.tARGET_QUANTITYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string UOM {
            get {
                return this.uOMField;
            }
            set {
                this.uOMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string SHORT_TEXT {
            get {
                return this.sHORT_TEXTField;
            }
            set {
                this.sHORT_TEXTField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> PRICE {
            get {
                return this.pRICEField;
            }
            set {
                this.pRICEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://Microsoft.LobServices.Sap/2007/03/Rfc/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://Microsoft.LobServices.Sap/2007/03/Rfc/", IsNullable=false)]
    public partial class Z_BIZ_BAPI_CONTRACT_CREATE1Response {
        
        private string tRANSACTION_IDField;
        
        private ZBAPI_RETURN rETURNField;
        
        private string sALESDOCUMENTField;
        
        private ZBAPI_CON_ITEM[] cONTRACT_ITEMField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string TRANSACTION_ID {
            get {
                return this.tRANSACTION_IDField;
            }
            set {
                this.tRANSACTION_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ZBAPI_RETURN RETURN {
            get {
                return this.rETURNField;
            }
            set {
                this.rETURNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string SALESDOCUMENT {
            get {
                return this.sALESDOCUMENTField;
            }
            set {
                this.sALESDOCUMENTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://Microsoft.LobServices.Sap/2007/03/Types/Rfc/", IsNullable=false)]
        public ZBAPI_CON_ITEM[] CONTRACT_ITEM {
            get {
                return this.cONTRACT_ITEMField;
            }
            set {
                this.cONTRACT_ITEMField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Microsoft.LobServices.Sap/2007/03/Types/Rfc/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://Microsoft.LobServices.Sap/2007/03/Types/Rfc/", IsNullable=true)]
    public partial class ArrayOfZBAPI_CON_ITEM {
        
        private ZBAPI_CON_ITEM[] zBAPI_CON_ITEMField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ZBAPI_CON_ITEM")]
        public ZBAPI_CON_ITEM[] ZBAPI_CON_ITEM {
            get {
                return this.zBAPI_CON_ITEMField;
            }
            set {
                this.zBAPI_CON_ITEMField = value;
            }
        }
    }
}
