//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sysmex.Crm.Plugins.SalesContract {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Z_BIZ_BAPI_CONTRACT_CREATE", Namespace="http://Microsoft.LobServices.Sap/2007/03/Rfc/")]
    [System.SerializableAttribute()]
    public partial class Z_BIZ_BAPI_CONTRACT_CREATE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private Sysmex.Crm.Plugins.SalesContract.ZBAPI_CON_HEADER CONTRACT_HEADERField;
        
        private Sysmex.Crm.Plugins.SalesContract.ZBAPI_CON_ITEM_TT[] CONTRACT_ITEMField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Sysmex.Crm.Plugins.SalesContract.ZBAPI_CON_HEADER CONTRACT_HEADER {
            get {
                return this.CONTRACT_HEADERField;
            }
            set {
                if ((object.ReferenceEquals(this.CONTRACT_HEADERField, value) != true)) {
                    this.CONTRACT_HEADERField = value;
                    this.RaisePropertyChanged("CONTRACT_HEADER");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Sysmex.Crm.Plugins.SalesContract.ZBAPI_CON_ITEM_TT[] CONTRACT_ITEM {
            get {
                return this.CONTRACT_ITEMField;
            }
            set {
                if ((object.ReferenceEquals(this.CONTRACT_ITEMField, value) != true)) {
                    this.CONTRACT_ITEMField = value;
                    this.RaisePropertyChanged("CONTRACT_ITEM");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ZBAPI_CON_HEADER", Namespace="http://Microsoft.LobServices.Sap/2007/03/Types/Rfc/")]
    [System.SerializableAttribute()]
    public partial class ZBAPI_CON_HEADER : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string DOC_TYPEField;
        
        private string SALES_ORGField;
        
        private string DISTR_CHANField;
        
        private string DIVISIONField;
        
        private string SOLD_TO_PARTYField;
        
        private string SHIP_TO_PARTYField;
        
        private string BILL_TO_PARTYField;
        
        private string PAYERField;
        
        private string PURCH_NO_CField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> PURCH_DATEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> CONTRACT_STARTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> CONTRACT_ENDField;
        
        private string BILLING_BLOCKField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> PRICE_DATEField;
        
        private string ORD_REASONField;
        
        private string SHIP_CONDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ADD_VAL_DYField;
        
        private string DEA_NUMBERField;
        
        private string CUST_GRP2Field;
        
        private string SHIP_TOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ZSITESField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ZTCOUNTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ZMCOUNTField;
        
        private string ZSTCOMField;
        
        private string ZMINMBILLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> ZKBETRField;
        
        private string ZCONIN5Field;
        
        private string ZCONIN4Field;
        
        private string ZCONIN6Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string DOC_TYPE {
            get {
                return this.DOC_TYPEField;
            }
            set {
                if ((object.ReferenceEquals(this.DOC_TYPEField, value) != true)) {
                    this.DOC_TYPEField = value;
                    this.RaisePropertyChanged("DOC_TYPE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string SALES_ORG {
            get {
                return this.SALES_ORGField;
            }
            set {
                if ((object.ReferenceEquals(this.SALES_ORGField, value) != true)) {
                    this.SALES_ORGField = value;
                    this.RaisePropertyChanged("SALES_ORG");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public string DISTR_CHAN {
            get {
                return this.DISTR_CHANField;
            }
            set {
                if ((object.ReferenceEquals(this.DISTR_CHANField, value) != true)) {
                    this.DISTR_CHANField = value;
                    this.RaisePropertyChanged("DISTR_CHAN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public string DIVISION {
            get {
                return this.DIVISIONField;
            }
            set {
                if ((object.ReferenceEquals(this.DIVISIONField, value) != true)) {
                    this.DIVISIONField = value;
                    this.RaisePropertyChanged("DIVISION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public string SOLD_TO_PARTY {
            get {
                return this.SOLD_TO_PARTYField;
            }
            set {
                if ((object.ReferenceEquals(this.SOLD_TO_PARTYField, value) != true)) {
                    this.SOLD_TO_PARTYField = value;
                    this.RaisePropertyChanged("SOLD_TO_PARTY");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public string SHIP_TO_PARTY {
            get {
                return this.SHIP_TO_PARTYField;
            }
            set {
                if ((object.ReferenceEquals(this.SHIP_TO_PARTYField, value) != true)) {
                    this.SHIP_TO_PARTYField = value;
                    this.RaisePropertyChanged("SHIP_TO_PARTY");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public string BILL_TO_PARTY {
            get {
                return this.BILL_TO_PARTYField;
            }
            set {
                if ((object.ReferenceEquals(this.BILL_TO_PARTYField, value) != true)) {
                    this.BILL_TO_PARTYField = value;
                    this.RaisePropertyChanged("BILL_TO_PARTY");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public string PAYER {
            get {
                return this.PAYERField;
            }
            set {
                if ((object.ReferenceEquals(this.PAYERField, value) != true)) {
                    this.PAYERField = value;
                    this.RaisePropertyChanged("PAYER");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public string PURCH_NO_C {
            get {
                return this.PURCH_NO_CField;
            }
            set {
                if ((object.ReferenceEquals(this.PURCH_NO_CField, value) != true)) {
                    this.PURCH_NO_CField = value;
                    this.RaisePropertyChanged("PURCH_NO_C");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public System.Nullable<System.DateTime> PURCH_DATE {
            get {
                return this.PURCH_DATEField;
            }
            set {
                if ((this.PURCH_DATEField.Equals(value) != true)) {
                    this.PURCH_DATEField = value;
                    this.RaisePropertyChanged("PURCH_DATE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public System.Nullable<System.DateTime> CONTRACT_START {
            get {
                return this.CONTRACT_STARTField;
            }
            set {
                if ((this.CONTRACT_STARTField.Equals(value) != true)) {
                    this.CONTRACT_STARTField = value;
                    this.RaisePropertyChanged("CONTRACT_START");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=11)]
        public System.Nullable<System.DateTime> CONTRACT_END {
            get {
                return this.CONTRACT_ENDField;
            }
            set {
                if ((this.CONTRACT_ENDField.Equals(value) != true)) {
                    this.CONTRACT_ENDField = value;
                    this.RaisePropertyChanged("CONTRACT_END");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=12)]
        public string BILLING_BLOCK {
            get {
                return this.BILLING_BLOCKField;
            }
            set {
                if ((object.ReferenceEquals(this.BILLING_BLOCKField, value) != true)) {
                    this.BILLING_BLOCKField = value;
                    this.RaisePropertyChanged("BILLING_BLOCK");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=13)]
        public System.Nullable<System.DateTime> PRICE_DATE {
            get {
                return this.PRICE_DATEField;
            }
            set {
                if ((this.PRICE_DATEField.Equals(value) != true)) {
                    this.PRICE_DATEField = value;
                    this.RaisePropertyChanged("PRICE_DATE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=14)]
        public string ORD_REASON {
            get {
                return this.ORD_REASONField;
            }
            set {
                if ((object.ReferenceEquals(this.ORD_REASONField, value) != true)) {
                    this.ORD_REASONField = value;
                    this.RaisePropertyChanged("ORD_REASON");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=15)]
        public string SHIP_COND {
            get {
                return this.SHIP_CONDField;
            }
            set {
                if ((object.ReferenceEquals(this.SHIP_CONDField, value) != true)) {
                    this.SHIP_CONDField = value;
                    this.RaisePropertyChanged("SHIP_COND");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=16)]
        public System.Nullable<int> ADD_VAL_DY {
            get {
                return this.ADD_VAL_DYField;
            }
            set {
                if ((this.ADD_VAL_DYField.Equals(value) != true)) {
                    this.ADD_VAL_DYField = value;
                    this.RaisePropertyChanged("ADD_VAL_DY");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=17)]
        public string DEA_NUMBER {
            get {
                return this.DEA_NUMBERField;
            }
            set {
                if ((object.ReferenceEquals(this.DEA_NUMBERField, value) != true)) {
                    this.DEA_NUMBERField = value;
                    this.RaisePropertyChanged("DEA_NUMBER");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=18)]
        public string CUST_GRP2 {
            get {
                return this.CUST_GRP2Field;
            }
            set {
                if ((object.ReferenceEquals(this.CUST_GRP2Field, value) != true)) {
                    this.CUST_GRP2Field = value;
                    this.RaisePropertyChanged("CUST_GRP2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=19)]
        public string SHIP_TO {
            get {
                return this.SHIP_TOField;
            }
            set {
                if ((object.ReferenceEquals(this.SHIP_TOField, value) != true)) {
                    this.SHIP_TOField = value;
                    this.RaisePropertyChanged("SHIP_TO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=20)]
        public System.Nullable<int> ZSITES {
            get {
                return this.ZSITESField;
            }
            set {
                if ((this.ZSITESField.Equals(value) != true)) {
                    this.ZSITESField = value;
                    this.RaisePropertyChanged("ZSITES");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=21)]
        public System.Nullable<int> ZTCOUNT {
            get {
                return this.ZTCOUNTField;
            }
            set {
                if ((this.ZTCOUNTField.Equals(value) != true)) {
                    this.ZTCOUNTField = value;
                    this.RaisePropertyChanged("ZTCOUNT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=22)]
        public System.Nullable<int> ZMCOUNT {
            get {
                return this.ZMCOUNTField;
            }
            set {
                if ((this.ZMCOUNTField.Equals(value) != true)) {
                    this.ZMCOUNTField = value;
                    this.RaisePropertyChanged("ZMCOUNT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=23)]
        public string ZSTCOM {
            get {
                return this.ZSTCOMField;
            }
            set {
                if ((object.ReferenceEquals(this.ZSTCOMField, value) != true)) {
                    this.ZSTCOMField = value;
                    this.RaisePropertyChanged("ZSTCOM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=24)]
        public string ZMINMBILL {
            get {
                return this.ZMINMBILLField;
            }
            set {
                if ((object.ReferenceEquals(this.ZMINMBILLField, value) != true)) {
                    this.ZMINMBILLField = value;
                    this.RaisePropertyChanged("ZMINMBILL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=25)]
        public System.Nullable<decimal> ZKBETR {
            get {
                return this.ZKBETRField;
            }
            set {
                if ((this.ZKBETRField.Equals(value) != true)) {
                    this.ZKBETRField = value;
                    this.RaisePropertyChanged("ZKBETR");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=26)]
        public string ZCONIN5 {
            get {
                return this.ZCONIN5Field;
            }
            set {
                if ((object.ReferenceEquals(this.ZCONIN5Field, value) != true)) {
                    this.ZCONIN5Field = value;
                    this.RaisePropertyChanged("ZCONIN5");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=27)]
        public string ZCONIN4 {
            get {
                return this.ZCONIN4Field;
            }
            set {
                if ((object.ReferenceEquals(this.ZCONIN4Field, value) != true)) {
                    this.ZCONIN4Field = value;
                    this.RaisePropertyChanged("ZCONIN4");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=28)]
        public string ZCONIN6 {
            get {
                return this.ZCONIN6Field;
            }
            set {
                if ((object.ReferenceEquals(this.ZCONIN6Field, value) != true)) {
                    this.ZCONIN6Field = value;
                    this.RaisePropertyChanged("ZCONIN6");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ZBAPI_CON_ITEM_TT", Namespace="http://Microsoft.LobServices.Sap/2007/03/Types/Rfc/")]
    [System.SerializableAttribute()]
    public partial class ZBAPI_CON_ITEM_TT : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string LINEITEM_IDField;
        
        private string MATERIAL_NUMBERField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> TARGET_QUANTITYField;
        
        private string UOMField;
        
        private string SHORT_TEXTField;
        
        private string ITEM_CATEGField;
        
        private string LINKEDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> PRICEField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string LINEITEM_ID {
            get {
                return this.LINEITEM_IDField;
            }
            set {
                if ((object.ReferenceEquals(this.LINEITEM_IDField, value) != true)) {
                    this.LINEITEM_IDField = value;
                    this.RaisePropertyChanged("LINEITEM_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string MATERIAL_NUMBER {
            get {
                return this.MATERIAL_NUMBERField;
            }
            set {
                if ((object.ReferenceEquals(this.MATERIAL_NUMBERField, value) != true)) {
                    this.MATERIAL_NUMBERField = value;
                    this.RaisePropertyChanged("MATERIAL_NUMBER");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> TARGET_QUANTITY {
            get {
                return this.TARGET_QUANTITYField;
            }
            set {
                if ((this.TARGET_QUANTITYField.Equals(value) != true)) {
                    this.TARGET_QUANTITYField = value;
                    this.RaisePropertyChanged("TARGET_QUANTITY");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string UOM {
            get {
                return this.UOMField;
            }
            set {
                if ((object.ReferenceEquals(this.UOMField, value) != true)) {
                    this.UOMField = value;
                    this.RaisePropertyChanged("UOM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public string SHORT_TEXT {
            get {
                return this.SHORT_TEXTField;
            }
            set {
                if ((object.ReferenceEquals(this.SHORT_TEXTField, value) != true)) {
                    this.SHORT_TEXTField = value;
                    this.RaisePropertyChanged("SHORT_TEXT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public string ITEM_CATEG {
            get {
                return this.ITEM_CATEGField;
            }
            set {
                if ((object.ReferenceEquals(this.ITEM_CATEGField, value) != true)) {
                    this.ITEM_CATEGField = value;
                    this.RaisePropertyChanged("ITEM_CATEG");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public string LINKED {
            get {
                return this.LINKEDField;
            }
            set {
                if ((object.ReferenceEquals(this.LINKEDField, value) != true)) {
                    this.LINKEDField = value;
                    this.RaisePropertyChanged("LINKED");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public System.Nullable<decimal> PRICE {
            get {
                return this.PRICEField;
            }
            set {
                if ((this.PRICEField.Equals(value) != true)) {
                    this.PRICEField = value;
                    this.RaisePropertyChanged("PRICE");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Z_BIZ_BAPI_CONTRACT_CREATEResponse", Namespace="http://Microsoft.LobServices.Sap/2007/03/Rfc/")]
    [System.SerializableAttribute()]
    public partial class Z_BIZ_BAPI_CONTRACT_CREATEResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private Sysmex.Crm.Plugins.SalesContract.ZBAPI_RETURN RETURNField;
        
        private string SALESDOCUMENTField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Sysmex.Crm.Plugins.SalesContract.ZBAPI_RETURN RETURN {
            get {
                return this.RETURNField;
            }
            set {
                if ((object.ReferenceEquals(this.RETURNField, value) != true)) {
                    this.RETURNField = value;
                    this.RaisePropertyChanged("RETURN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string SALESDOCUMENT {
            get {
                return this.SALESDOCUMENTField;
            }
            set {
                if ((object.ReferenceEquals(this.SALESDOCUMENTField, value) != true)) {
                    this.SALESDOCUMENTField = value;
                    this.RaisePropertyChanged("SALESDOCUMENT");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ZBAPI_RETURN", Namespace="http://Microsoft.LobServices.Sap/2007/03/Types/Rfc/")]
    [System.SerializableAttribute()]
    public partial class ZBAPI_RETURN : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string TYPEField;
        
        private string MESSAGEField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string TYPE {
            get {
                return this.TYPEField;
            }
            set {
                if ((object.ReferenceEquals(this.TYPEField, value) != true)) {
                    this.TYPEField = value;
                    this.RaisePropertyChanged("TYPE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public string MESSAGE {
            get {
                return this.MESSAGEField;
            }
            set {
                if ((object.ReferenceEquals(this.MESSAGEField, value) != true)) {
                    this.MESSAGEField = value;
                    this.RaisePropertyChanged("MESSAGE");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://sws.sysmex.com/CPQSAPWebService/SalesContract/", ConfigurationName="SalesContract.SalesContractSoap")]
    public interface SalesContractSoap {
        
        // CODEGEN: Generating message contract since element name Z_BIZ_BAPI_CONTRACT_CREATE from namespace http://Microsoft.LobServices.Sap/2007/03/Rfc/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://sws.sysmex.com/CPQSAPWebService/SalesContract/SalesContract/Create", ReplyAction="*")]
        Sysmex.Crm.Plugins.SalesContract.CreateResponse Create(Sysmex.Crm.Plugins.SalesContract.CreateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sws.sysmex.com/CPQSAPWebService/SalesContract/SalesContract/Create", ReplyAction="*")]
        System.Threading.Tasks.Task<Sysmex.Crm.Plugins.SalesContract.CreateResponse> CreateAsync(Sysmex.Crm.Plugins.SalesContract.CreateRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Create", Namespace="http://sws.sysmex.com/CPQSAPWebService/SalesContract/", Order=0)]
        public Sysmex.Crm.Plugins.SalesContract.CreateRequestBody Body;
        
        public CreateRequest() {
        }
        
        public CreateRequest(Sysmex.Crm.Plugins.SalesContract.CreateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Microsoft.LobServices.Sap/2007/03/Rfc/")]
    public partial class CreateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Sysmex.Crm.Plugins.SalesContract.Z_BIZ_BAPI_CONTRACT_CREATE Z_BIZ_BAPI_CONTRACT_CREATE;
        
        public CreateRequestBody() {
        }
        
        public CreateRequestBody(Sysmex.Crm.Plugins.SalesContract.Z_BIZ_BAPI_CONTRACT_CREATE Z_BIZ_BAPI_CONTRACT_CREATE) {
            this.Z_BIZ_BAPI_CONTRACT_CREATE = Z_BIZ_BAPI_CONTRACT_CREATE;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateResponse", Namespace="http://sws.sysmex.com/CPQSAPWebService/SalesContract/", Order=0)]
        public Sysmex.Crm.Plugins.SalesContract.CreateResponseBody Body;
        
        public CreateResponse() {
        }
        
        public CreateResponse(Sysmex.Crm.Plugins.SalesContract.CreateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://Microsoft.LobServices.Sap/2007/03/Rfc/")]
    public partial class CreateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Sysmex.Crm.Plugins.SalesContract.Z_BIZ_BAPI_CONTRACT_CREATEResponse Z_BIZ_BAPI_CONTRACT_CREATEResponse;
        
        public CreateResponseBody() {
        }
        
        public CreateResponseBody(Sysmex.Crm.Plugins.SalesContract.Z_BIZ_BAPI_CONTRACT_CREATEResponse Z_BIZ_BAPI_CONTRACT_CREATEResponse) {
            this.Z_BIZ_BAPI_CONTRACT_CREATEResponse = Z_BIZ_BAPI_CONTRACT_CREATEResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SalesContractSoapChannel : Sysmex.Crm.Plugins.SalesContract.SalesContractSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SalesContractSoapClient : System.ServiceModel.ClientBase<Sysmex.Crm.Plugins.SalesContract.SalesContractSoap>, Sysmex.Crm.Plugins.SalesContract.SalesContractSoap {
        
        public SalesContractSoapClient() {
        }
        
        public SalesContractSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SalesContractSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SalesContractSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SalesContractSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Sysmex.Crm.Plugins.SalesContract.CreateResponse Sysmex.Crm.Plugins.SalesContract.SalesContractSoap.Create(Sysmex.Crm.Plugins.SalesContract.CreateRequest request) {
            return base.Channel.Create(request);
        }
        
        public Sysmex.Crm.Plugins.SalesContract.Z_BIZ_BAPI_CONTRACT_CREATEResponse Create(Sysmex.Crm.Plugins.SalesContract.Z_BIZ_BAPI_CONTRACT_CREATE Z_BIZ_BAPI_CONTRACT_CREATE) {
            Sysmex.Crm.Plugins.SalesContract.CreateRequest inValue = new Sysmex.Crm.Plugins.SalesContract.CreateRequest();
            inValue.Body = new Sysmex.Crm.Plugins.SalesContract.CreateRequestBody();
            inValue.Body.Z_BIZ_BAPI_CONTRACT_CREATE = Z_BIZ_BAPI_CONTRACT_CREATE;
            Sysmex.Crm.Plugins.SalesContract.CreateResponse retVal = ((Sysmex.Crm.Plugins.SalesContract.SalesContractSoap)(this)).Create(inValue);
            return retVal.Body.Z_BIZ_BAPI_CONTRACT_CREATEResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Sysmex.Crm.Plugins.SalesContract.CreateResponse> Sysmex.Crm.Plugins.SalesContract.SalesContractSoap.CreateAsync(Sysmex.Crm.Plugins.SalesContract.CreateRequest request) {
            return base.Channel.CreateAsync(request);
        }
        
        public System.Threading.Tasks.Task<Sysmex.Crm.Plugins.SalesContract.CreateResponse> CreateAsync(Sysmex.Crm.Plugins.SalesContract.Z_BIZ_BAPI_CONTRACT_CREATE Z_BIZ_BAPI_CONTRACT_CREATE) {
            Sysmex.Crm.Plugins.SalesContract.CreateRequest inValue = new Sysmex.Crm.Plugins.SalesContract.CreateRequest();
            inValue.Body = new Sysmex.Crm.Plugins.SalesContract.CreateRequestBody();
            inValue.Body.Z_BIZ_BAPI_CONTRACT_CREATE = Z_BIZ_BAPI_CONTRACT_CREATE;
            return ((Sysmex.Crm.Plugins.SalesContract.SalesContractSoap)(this)).CreateAsync(inValue);
        }
    }
}
